version: '3.1'

services:
    web:
        image: nginx:latest
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        ports:
         - "8000:80"
        links:
            - php
    php:
        build: ./images/php
        links:
            - db
        volumes: 
            - ./www:/var/www
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_PASSWORD: example
            MYSQL_USER: root
        links:
            - phpmyadmin    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports: 
            - "8080:80"
        volumes:
        - /sessions